### ISSUE TITLE
Verify clipboard contents before getting data

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/win32yank#1]
As reported by @mqudsi in https://github.com/neovim/neovim/issues/6227#issuecomment-284578955

See https://retep998.github.io/doc/user32/fn.EnumClipboardFormats.html

**Comment by equalsraf** [comment]
Interesting, while testing https://github.com/equalsraf/win32yank/pull/2 it seems that if the clipboard does not have the format, it does return an error, not gibberish data.

**Comment by equalsraf** [comment]
Closed by #2

**Comment by mqudsi** [comment]
Forgive me, I was running into a different error when binary data was copied to the clipboard.
