### ISSUE TITLE
PKGBUILD for Arch Linux if anyone needs it

### ISSUE THREAD

**Issue by IgnusG** [equalsraf/win32yank#12]
Wanted to get this tool working for neovim <-> WSL clipboard sharing so I built a PKGBUILD for Arch if anyone needs it.

https://github.com/IgnusG/win32yank-pkgbuild

```bash
# Clone repo
git clone  https://github.com/IgnusG/win32yank-pkgbuild

# Package & Install
makepkg -fsri
```

Don't forget to [add `set clipboard=unnamedplus` to your neovim config](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl)

**Comment by ChiliYe** [comment]
thank for your PKGBUILD
