### ISSUE TITLE
Installation Instructions From Main Branch?

### ISSUE THREAD

**Issue by riotrah** [equalsraf/win32yank#13]
Hi!

Firstly, thanks for this work.

Pardon my inexperience with Rust tooling. It appears that tho there have been ostensibly relevant commits, those changes have not been released or tagged.

What's the recommended way to install the latest state of this repo? Or do you think it's fine to install the last release from 2017?

Thanks again

**Comment by danieldides** [comment]
I noticed the same thing. I'm not sure if the changes have been meaningful but the release is over 4 years old at this point. Building from source was painless though. I just installed Rust (in Windows) and run `cargo build --release` and then moved the resulting binary in `target/release` to my desired destination. Hopefully this helps.

**Comment by equalsraf** [comment]
The changes after the last tag were not meaningful. They fixed some issues with continuous integration and cleaned up some unused imports.

For installing from source you can either move the binary (after cargo build) - or maybe do a `cargo install --path . ` but I dont know where that will install the binary in windows.
