### ISSUE TITLE
Unresolved Imports when building 

### ISSUE THREAD

**Issue by Antonio-Bennett** [equalsraf/win32yank#17]
Hello sorry for my ignorance but I'm trying to build [win32yank](https://github.com/equalsraf/win32yank) and I keep getting unresolved import error as seen below. What is the possible reason?
![image](https://user-images.githubusercontent.com/31296212/210849612-ff93b24e-b587-4ced-921e-ba67163dda80.png) 
![image](https://user-images.githubusercontent.com/31296212/210849697-addf2692-64a5-4010-b3bb-47c917f8115e.png)

**Comment by mariansimecek** [comment]
I have the same problem

**Comment by casret** [comment]
If you are building from linux, you'll need to cross compile. `cargo build --target x86_64-pc-windows-gnu -r`

**Comment by jemag** [comment]
Thanks for the info @casret , had a problem with the linker with the cross compilation command however: 
![image](https://user-images.githubusercontent.com/7985687/210886199-a2245af8-e4ef-48d1-9476-8594c8d6e05d.png)
Ended up using https://github.com/cross-rs/cross to do it

Basically 
`cargo clean`
then
`cross build --target x86_64-pc-windows-gnu`
 which worked for me

**Comment by gaving** [comment]
Cheers @jemag - `cross` did the trick for me too!

**Comment by equalsraf** [comment]
Correct, win32yank is a native windows application (calls the windows clipboard API). To build it from linux or wsl you will always need to cross compile, or build using the native windows toolchain instead.
