### ISSUE TITLE
System requirements?

### ISSUE THREAD

**Issue by mkpaz** [equalsraf/win32yank#4]
It seems like win32yank requires at least Windows 7 SP1. When I'm trying to execute `win32yank -o` from cli it complains about missing dlls. In particular `VCRUNTIME140.dll` and `api-ms-win-crt-runtime-l1-1-0-dll`. These dlls corresponds to VC++ 2015 Redistributable and KB2999226 Update packages.
Both of them requires SP1 to be installed.

Since I don't have plans to upgrade target PC (because some of proprietary apps requires specific IE version) it seems like my neovim journey has ended. :)

I think it's worth to add this to readme so the other people don't waste their time.

**Comment by equalsraf** [comment]
Updated
